### ISSUE TITLE
Cannot break sign

### ISSUE THREAD

**Issue by Artuto** [serversigns/ServerSigns#10]
I'm using SVS version 4.5.2 for Minecraft 1.14.4 (Paper).

When I break a serversign, the sign file does get deleted, but i cant place another block in the place the sign was. Doing /svs reload does not fix the issue.

**Comment by Artuto** [comment]
After further investigation it seems like I just can't interact with anything on the world; restarting the server fixed it.

**Comment by EpiCanard** [comment]
When you can't interact with anything try /svs void. If the issue come from SVS it should fix the issue, else it's maybe somewhere else.

Is your issue is fixed ? It can be closed ?

**Comment by Artuto** [comment]
I consider this should considered a bug, and I shouldnt need to run a command to regain control over my world for some reason? At least a message in the chat would be nice to know whats happening, but nothing in the console nor the chat

**Comment by EpiCanard** [comment]
If there is no clear way to reproduce the bug it will be difficult to find it inside the plugin
When I do the steps you explained I have no error I can continue to place block

**Comment by EpiCanard** [comment]
The last version released should fix your issue, all pending commands are cleared on reload.
https://dev.bukkit.org/projects/serversigns/files/2915106
