### ISSUE TITLE
Full vault support (Was an issue with own plugin)

### ISSUE THREAD

**Issue by Stualyttle** [serversigns/ServerSigns#13]
Heye!

We had a little problem with the economy option for ServerSigns. 

When we were using Essentials back in 1.12.2 ([https://papermc.io/ci/job/Paper/](https://papermc.io/ci/job/Paper/)) it worked fine.

But since 1 month we have updated to 1.14.4 ([https://papermc.io/ci/job/Paper-1.14/](https://papermc.io/ci/job/Paper-1.14/)) and we created our own plugin (and removed Essentials), that works with [Vault](https://github.com/milkbowl/Vault) I don't know if 1.14.4 broke it, but the only thing I know is your plugin is the only one that the economy does not work. Our ChestCommands, Crates, Info-Board & other custom plugins work fine with the new plugin and Vault.

I wanted to report this because I love this plugin, its amazing and a life changing plugin. Maybe you have the same problem..

Thanks in advance!
~Stualyttle

**Comment by EpiCanard** [comment]
Hello, thanks for the bug report :)
Which version of Serversigns do you use ?
And what is the economy plugin do you use ? Is it public ?

I see the compilation vault version is 1.5 inside serversigns and the last one is 1.7 maybe it is the reason.

**Comment by Stualyttle** [comment]
Heye,

I'm using ServerSigns version [v4.5.3](http://ci.serversigns.de/job/ServerSigns/31/) (latest as i'm aware of)
No, my economy plugin (Our wn Essentials) is private for my server, and made by its developpers. I could give you the contact details of my developper, so he could give you the code needed.

I think updating the [vault](https://github.com/milkbowl/Vault) api implemention will fix it, since Vault changed a bit since 2016.

Thanks in advance!
~Stualyttle

**Comment by EpiCanard** [comment]
I will try to update Vault and you will tell me if all works as expect.

If it don't works, yes maybe I will need to contact your developer :)

**Comment by EpiCanard** [comment]
Does this version fix the issue ? https://drive.google.com/open?id=11TIQ_YRlmZhun_SATV8sNy_FuqeIbgzf

**Comment by Stualyttle** [comment]
Heye!

I've tried it, and it does not work. 
**Edit 2:** (Stopped Server, Removed old plugin, uploaded new plugin and started it again)*
![image](https://cdn.stualyttle.com/wk6G8vCB5P.png)
I also tried the crates plugin and that one does work, and my money changes..

Any ideas why?

**Edit 1:** PS: I'm also using your version: 
![image](https://cdn.stualyttle.org/6TA2SBGuEH.png)

Greets,
~Stualyttle

**Comment by EpiCanard** [comment]
Hello,

So there is really a bug.
Thanks for your help I will search more deeply to find the bug.
Can you send me in private message (on spigot for example) a jar of your economy plugin ? It can help me to find and fix the issue.

Thanks in advance
EpiCanard

**Comment by Stualyttle** [comment]
Heye!

I've contacted you on [Spigot](https://www.spigotmc.org/conversations/full-vault-support-github-topic.382473/). Please do not share this plugin with others ;-) 

Also, my developper said if you wanted the source code, you could have it, (again not share it) but he also sead, that you could read the source code from the file itself.

Thanks for the help so far!
~Stualyttle

**Comment by EpiCanard** [comment]
Hello,

Thank you for the file.
Don't worry I will not share it.

Just this file should be enough to help me to find the bug.

Best regards,
EpiCanard

**Comment by EpiCanard** [comment]
Hello,

It seems there is a bug inside your plugin. Inside your SWEconomy that implement vault economy you have a method
```
  public boolean has(@Nullable OfflinePlayer p0, double p1)
  {
    return p1 >= getBalance(p0);
  }
```

You are checking that the wanted price is higher than your total price and not the opposite as it should be.

Can you see with you developer to fix it ?
Oh and you have another bug when you start your plugin for the first time, the plugin folder is not well created, I had to create it myself.
And you can remove money without limit and go behind zero. And your reset message when you do `/eco reset` the player is not well displayed.

I guess if it works with other plugins it's because they use `getBalance()` and compare the price themself. But here ServerSign use `has()` that do the same but shorter.

Best regards,
EpiCanard

**Comment by Stualyttle** [comment]
Heye,

I've contacted our dev, he will be looking into it!
Thanks for the help so far, lets take a look if that fixes it.

The bug that the folder does not create is known, but since we use the plugin only we didn't bother fixing it since we already copy'd these around :P 

Now its waiting time till the dev fixes it, i will contact you here, if i have more information.

Greets,
~Stualyttle

**Comment by EpiCanard** [comment]
Hello @Stualyttle,

Any News about this issue ? Did you fix your Economy plugin ?

Best regards,
EpiCanard

**Comment by JohnyTheCarrot** [comment]
Hi, said developer here. I had been busy with exams but I'm on it now!

**Comment by EpiCanard** [comment]
Hello @JohnyTheCarrot ,

Ok :)

Thanks for your quick answer

Best regards,
EpiCanard

**Comment by Stualyttle** [comment]
Heye!

The issue has been resolved by my developer, 
I will close this issue as it is no longer a leading issue

I want to thank you VERY MUCH for the help you have provided, and the patience you had!
There are a lot of developers who would not have done what you have done, 
I want to thank you for that!

Best regards,
~Stualyttle

**Comment by EpiCanard** [comment]
Hello

Cool :)

It's normal for me, that from the moment I maintain a plugin to provide support to players and help them to fix their problems. Even more when people are kind and respectful.

Best regards and good luck for the future
EpiCanard
