### ISSUE TITLE
add support for PlaceholderAPI, &/or add group-of-signs-cooldown

### ISSUE THREAD

**Issue by leasoncre** [serversigns/ServerSigns#18]
Can you add support for PlaceholderAPI variables please?
I've seen alot of PlaceholderAPI-suppported plugins lately.

I'm using LuckPerms's temp-perm to setup a group of signs that can only be used every so often (prevent spamming across all the signs that do very similar actions) since i don't see that functionality supported through SVS atm. (idea: /svs scd 5m g:prefixsigns )
ex: "/svs sp serversigns.use.suffixsigns m:&e&lYou must wait &c%luckperms_expiry_time_serversigns.use.prefixsigns%&e&l to use prefix signs again." - this is currently working, but PAPI isn't being parsed :(

Thank you.

**Comment by EpiCanard** [comment]
Hello,

There is already a feature to support PAPI but not yet released #16. But it only support PAPI for <if> operator.

You want to add the support to every message displayed ?

**Comment by leasoncre** [comment]
@#16 cool, but i was trying to parse the value in the message (print value), not test for it in my case.
that was the idea, parse PAPI values through any compatible method. (msg,sp,etc.. not sure what else since PAPI requires a player to be parsed at all)

alternatively to using a fancy perm system to manage a group of signs's cooldown(shared) (i doubt some older perm systems have perm expiry abilities), was to add the capability to serversigns directly. (secondary idea)

**Comment by EpiCanard** [comment]
Added, need more test to verify all works as expected and make a release

**Comment by EpiCanard** [comment]
Fixed and released in v4.6.0
