### ISSUE TITLE
Can't click signs

### ISSUE THREAD

**Issue by ArchieIrving** [serversigns/ServerSigns#24]
Hey,
When I try to create a ServerSign it isn't letting me click a sign after I've used the command. The action is there, but it isn't putting the command on the sign I'm clicking. I'm using latest version of ServerSignsand Spigot 1.15.2

**Comment by EpiCanard** [comment]
Hello :)


Have you gone from an old version to a new one without resetting your configuration file or is this a new installation?

What command are you trying to add to the sign?

Is your problem still present with the latest development version?  http://ci.serversigns.de/job/ServerSigns-dev-builds/7/

**Comment by ArchieIrving** [comment]
Hey, I tried that latest development build and it fixed the issue.

The command I'm using is <server> tp <player> <coords>
Do you happen to know if there's a way to teleport a player to a location but make them face a specific direction?

**Comment by EpiCanard** [comment]
Hello,

Good, it should be a bug that has been fixed but not yet released.

If you use command tp you can use **yaw** and **pitch**, see this wiki : https://minecraft.gamepedia.com/Commands/tp/Before_Java_Edition_17w45a
Or if  you use command execute you can use **facing**, see this wiki :
https://minecraft.gamepedia.com/Commands/teleport

**Comment by ArchieIrving** [comment]
Thanks for your help!
