### ISSUE TITLE
some commands missing permission system handling

### ISSUE THREAD

**Issue by leasoncre** [serversigns/ServerSigns#25]
**/svs import** is not included in **serversigns.admin** nor is there a node for it **serversigns.import**
https://serversigns.de/wiki/Permissions
(only ops can use) :/

ServerSigns version 4.6.1 | Paper 1.15.2

**Comment by EpiCanard** [comment]
**serversigns.command.import** doesn't works ?
He may have just been forgotten.
I will add it in **serversigns.admin** and in wiki

**Comment by leasoncre** [comment]
oh, derp, i didn't try that specifically.. been muddleing through a bunch of other plugin's perms and they use pluginname.<command> instead of pluignname.command.<actualcommand> :/
i will try that later on. (pending a look at few other issues/testing)

**Comment by EpiCanard** [comment]
The wiki has been updated https://serversigns.de/wiki/Permissions
And all the commands has been added in **plugin.yml** in last dev-build https://ci.serversigns.de/job/ServerSigns-dev-builds/8/

Other change, the permission **serversigns.command.cooldown_reset** has been renamed to **serversigns.command.reset_cooldown** (as it was in the wiki but not in the plugin)
