### ISSUE TITLE
PAPI placeholders parsed during /svs info output

### ISSUE THREAD

**Issue by leasoncre** [serversigns/ServerSigns#26]
Minor issue:
**/svs info** parses the PAPI Placeholder. It should display the raw placeholder text. (potentially confusing) :/
Minor bug. code works :)

ServerSigns version 4.6.1 | Paper 1.15.2

**Comment by EpiCanard** [comment]
Oh :') I made all Text displayed by the plugin usable with PlaceholderAPI. I didn't think about this side effect ^^

**Comment by leasoncre** [comment]
yeah, the ONE place it shouldn't be parsed ><
(and/or any other info commands, but i can't think of any)
though i would say it is somewhat useful to see what values it's reading. BUT you can do that with /papi parse beforehand to see what it's producing anyway

**Comment by EpiCanard** [comment]
Yep, with svs info you should see the final result parsed :)

**Comment by leasoncre** [comment]
> Yep, with svs info you should see the final result parsed :)

uh. that sounds backwards to me, it should show the raw placeholder, not a parsed value

**Comment by EpiCanard** [comment]
No my bad I forgot the negation 
*You should not
Sorry I just forgot a word ^^"

**Comment by EpiCanard** [comment]
Fixed, will be in next release
