### ISSUE TITLE
Paper+SVS

### ISSUE THREAD

**Issue by leasoncre** [serversigns/ServerSigns#28]
trying to setup a tempfly sign (still testing)
but it's just not working as expected.
looks at console: why no like paper... >_>

logs/files attached
Client log: what i did
Console Log: Error spam ><
Flytest: commands for /svs import (latest revision in attempt to get this working. have moved changes a number of things throughout testing)

[client log.txt](https://github.com/serversigns/ServerSigns/files/4624752/client.log.txt)
[Console log.txt](https://github.com/serversigns/ServerSigns/files/4624753/Console.log.txt)
[FlyTEST.txt](https://github.com/serversigns/ServerSigns/files/4624754/FlyTEST.txt)

Paper 1.15.2-283 | ServerSigns version 4.6.1

**Comment by EpiCanard** [comment]
I have no idea what is going on, all seems ok in your imported file.

I know that asynchronous command can be an issue, so maybe the delay with command can be the cause, but it even crash on the first command with no delay, I don't understand.

**Comment by EpiCanard** [comment]
The bug seems to appear when there is a confirm inside the sign. Did you find other situations where the bug appear ?

**Comment by EpiCanard** [comment]
Fixed. Will be in next release :)
