### ISSUE TITLE
Option to disable a message

### ISSUE THREAD

**Issue by Annorit24** [serversigns/ServerSigns#34]
Dear developers,

I recently discover the plugin Server Sign and inter alia the system of Q&A of the plugin. I tried to test the plugin but I discovered that when a player answers the question, the message "OK" is sent by the plugin. I search a way to disable this message but I found that it is always sent ( 
ServerSigns/src/main/java/de/czymm/serversigns/signs/PlayerInputOptionsManager.java line 84).

Maybe you can disable this message when the silent value of a sign is set to true?

Yours sincerely,
Annorit24

**Comment by EpiCanard** [comment]
Thank you for the the bug report, I'll fix it as soon as I have time :)

**Comment by EpiCanard** [comment]
Bug fixed.

You can find the last deb build here : https://ci.serversigns.de/job/ServerSigns-dev-builds/10/
