### ISSUE TITLE
"Nag author" error

### ISSUE THREAD

**Issue by Srborjaa** [serversigns/ServerSigns#35]
![imagen](https://user-images.githubusercontent.com/29895095/84534247-dc346480-ace9-11ea-9859-56871a8f7708.png)

Hi, when I stop the server using /stop, /restart and /reload, this error appears. I've seen that another plugin "Signshop" is showing that error but I don't know why.

**Comment by EpiCanard** [comment]
Can you give more information ?
Which version of ServerSigns and Minecraft Server (bukkit, etc) do you use ?

**Comment by EpiCanard** [comment]
Fixed, will be in next release
