### ISSUE TITLE
Dupe issue

### ISSUE THREAD

**Issue by Artuto** [serversigns/ServerSigns#37]
We have had a player use a sign that had a item price to dupe the execution of the commands without removing the item.

I do not feel like publishing how it is done, how can I contact you?

**Comment by EpiCanard** [comment]
You can contact me on [spigot](https://www.spigotmc.org/conversations/add?to=EpiCanard) or by mail to epicanard@gmail.com

**Comment by Artuto** [comment]
I've sent you a DM on Spigot

**Comment by EpiCanard** [comment]
Oh ok I see, thank you for you report. I see more or less where is the bug.

Sorry, sadly I don't have much free time I will fix it when I will have the time. :/

Note for me: `InventoryUtils.scan`

**Comment by Artuto** [comment]
If I can figure it out I'll throw you a PR

**Comment by EpiCanard** [comment]
Thank you :)

**Comment by EpiCanard** [comment]
Hello, 

@Artuto I tried to reproduce the bug with 1.16 version and I didn't succeed, everything works as expected.
Which version of minecraft and svs do you use ?

**Comment by EpiCanard** [comment]
@Artuto It seems to be an error that happen only with paper 1.16. With paper 1.15 or spigot 1.15/1.16 it works as expected.

**Comment by EpiCanard** [comment]
I tried with multiple versions : spigot 1.15 and 1.16, paper 1.15 and 1.16 and it always works as expected.

I close this issue, please reopen it if you still have the bug.
