### ISSUE TITLE
[Suggestion] Development builds of current repository

### ISSUE THREAD

**Issue by EpiCanard** [serversigns/ServerSigns#4]
Issue goal :
Suggestion

Description :
Can you edit your job jenkins http://ci.serversigns.de/job/ServerSigns/ to build the GitHub sources and not your private repository ? That people can benefit from latest development builds of current Github.

Thanks in advance for your answer

**Comment by czymstef** [comment]
https://ci.serversigns.de/job/ServerSigns/ will now build the master branch of this repository

**Comment by EpiCanard** [comment]
Thanks a lot !
