### ISSUE TITLE
Cancel deletion after any interaction and output a sign wasn't found.

### ISSUE THREAD

**Issue by mibby** [serversigns/ServerSigns#43]
If you type ``/svs delete`` and click on an SVS sign / button, it removes it. However if you typed it again (or just in general) and there is _no_ valid svs sign to delete, you can't interact with blocks (place or break), buttons, or signs until SVS completes its action. I propose either a timeout or cancelling the delete on an interact with an invalid block.

Relogging doesn't fix SVS cancelling interactions, nor does reloading with ``/svs reload``. You either need to find an SVS sign somewhere to stop it or force a server restart.

**Comment by EpiCanard** [comment]
Hello,

You can use `/svs void` to cancel pending svs actions.

**Comment by mibby** [comment]
Ah, I didn't know about that command! That does work instead, thanks. Just didn't want to get stuck in a breaking loop.

**Comment by EpiCanard** [comment]
No problem :)
