### ISSUE TITLE
consume item as part of an if statement

### ISSUE THREAD

**Issue by aparry91** [serversigns/ServerSigns#47]
I finally got my if statement setup to use this god awful long minecraft:clear command with all the tag structure of the custom item,
used svs long to add it, however it does not behave in the correct way

Is there a way to utilise the price item cost within a conditional?

**Comment by EpiCanard** [comment]
Actually no, it's not possible.
The price item cost is always the same, so you can directly add it to the command

**Comment by aparry91** [comment]
Ah right, I have mostly done this because I would like to right click the sign with the item held, rather than it being anywhere in my inventory, did I miss an option to do that??

My conditional basically sent a message if the player needed to find an item, or if the player had the item but needed to equip it and finally if they had it in their hand, it would be the positive track.

In the positive track I was trying to remove the item using minecraft:clear, the command works in console, but when trying to add it via /svs long it doesn't work, is this something to do with how an system command runs the command ? Or is this because my svs long command is not read properly due to the syntax of the command (it has alot of Json in there for all the description and name)

The error message indicates that it is searching my player for the item, but it can't find the item.
Makes me think something is happening to the Json format

**Comment by EpiCanard** [comment]
> Ah right, I have mostly done this because I would like to right click the sign with the item held, rather than it being anywhere in my inventory, did I miss an option to do that??

No you didn't missing, the price item will be check on all inventory there is no option to specify if it must be in hand.

> My conditional basically sent a message if the player needed to find an item, or if the player had the item but needed to equip it and finally if they had it in their hand, it would be the positive track.

Maybe there is a minecraft command to get the position in inventory of the item but currently with SVS the customization doesn't go that far ^^

> In the positive track I was trying to remove the item using minecraft:clear, the command works in console, but when trying to add it via /svs long it doesn't work, is this something to do with how an system command runs the command ? Or is this because my svs long command is not read properly due to the syntax of the command (it has alot of Json in there for all the description and name)

Maybe one of characters used is badly parsed ? If you use import command instead of long ? ( Use bukkit version, spigot is not up to date)

Can you send me the command you are trying to do ?

**Comment by aparry91** [comment]
> Maybe there is a minecraft command to get the position in inventory of the item but currently with SVS the customization doesn't go that far ^^

Yep , I managed to use the placeholder api to check for my custom items lore and also if the item is in the hand! I can show you all of those if you're interested

I took the jar from latest release tag I think, I did think its probably a parsing thing.

I can send over the command on Saturday, not at my computer until then, I'll also try the import command, sounds like I might have a bit more luck with that!

**Comment by EpiCanard** [comment]
Hum ok :P

With import command you don't have the limitation of the chat size so maybe you will have more luck :)

**Comment by aparry91** [comment]
Alright so I tried the /svs import command

I've tried it with a simple command such as /say hi
saved it as commands.txt in the ServerSigns directory, used /svs import commands.txt
it prompts me to right click a sign with a command so I do,
following this I get a red out put saying, Unable to execute "/say hi" as no matching commands were found.
Then another output line in yellow saying, successfully imported the file "commands.txt"

**Comment by EpiCanard** [comment]
The import command is like other command so you must put the keyword before like

`add say hi`
Is equivalent to
`/svs add say hi`

**Comment by aparry91** [comment]
Hallelujah mate! that was it, thank you so much :)

I have one final thing, I managed to get placeholders working by installing the placeholder api and registering it with the /papi commands, is that all we can do? I would like to use {player} or placeholder:%player_name% in non vanilla commands and non <msg> commands, do you know if this possible?

**Comment by EpiCanard** [comment]
> I have one final thing, I managed to get placeholders working by installing the placeholder api and registering it with the /papi commands, is that all we can do?

This the way how it works yes?

> I would like to use {player} or placeholder:%player_name% in non vanilla commands and non commands, do you know if this possible?

What do you mean ? If just want to use player_name, serversigns has native placeholder `<player>`

**Comment by aparry91** [comment]
that was the missing piece, thankyou so much :)
