### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by BradTheGoose** [serversigns/ServerSigns#49]
I use svs to allow players to rankup from rank0 to rank1, rank2 , ...., rank13 but I have 2 problems:

1) A player that has a rank and clicks on any rankup sign, pays every time even if he already got that rank. Is it possible to add an if to check a players rank before he pays?

2) Is it possible to do something like: 
if(condition){
command1
command2
commadn3
}
all I've been able to do is:
if(condition)
command1
if(condition)
command2
if(condition)
command3

**Comment by EpiCanard** [comment]
Hello,

**Comment by EpiCanard** [comment]
Hello,

1. If you don't want to have the price take each time you can use directly the command of your economy plugin in the sign
2. You can delimit it with <if> <endif>

Example :
```
/svs add <if> hasPerm:rank1
/svs add <server> lp user <player> promote rank2
/svs add <server> eco take <player> 42
/svs add <return>
/svs add <endif>

/svs add <if> hasPerm:rank2
/svs add <server> lp user <player> promote rank3
/svs add <server> eco take <player> 84
/svs add <return>
/svs add <endif>
```

**Comment by BradTheGoose** [comment]
Thanks, the 2° point is exactly what I needed but in the first one, won't the players rankup even if they don't have enough money?

**Comment by EpiCanard** [comment]
You  can maybe do something like that, but you will need placeholderApi and the placeholder extension for vault.

```
/svs add <if> hasPerm:rank1
/svs add <if> placeholder:%vault_eco_balance%>42
/svs add <server> lp user <player> promote rank2
/svs add <server> eco take <player> 42
/svs add <return>
/svs add <endif>
/svs add <endif>

/svs add <if> hasPerm:rank2
/svs add <if> placeholder:%vault_eco_balance%>84
/svs add <server> lp user <player> promote rank3
/svs add <server> eco take <player> 84
/svs add <return>
/svs add <endif>
/svs add <endif>
```

**Comment by BradTheGoose** [comment]
daaaamn thanks I didnt know about placeholderApi. This solves everything 😄

**Comment by EpiCanard** [comment]
Yep it's a really useful feature :)

Problem solved, I close the issue.
