### ISSUE TITLE
Error Minecraft server 1.14

### ISSUE THREAD

**Issue by colo13verdadeo** [serversigns/ServerSigns#5]
When /svs add (command) and seted, when clicking sign not execute command ""Unknown command. Thpe "/help" for help". 

Image:
https://cdn.discordapp.com/attachments/620779876298915860/623292807418871819/unknown.png

I have last version (http://ci.serversigns.de/job/ServerSigns/29/)

**Comment by EpiCanard** [comment]
Which command are you trying to launch ?
This command must be executed by the player or by the server ?
Does the player that click on the sign has permissions to execute the command ?

**Comment by EpiCanard** [comment]
No answer, I close this issue.
If your error is still here please reopen this issue.
