### ISSUE TITLE
uuid not found when using <uuid>

### ISSUE THREAD

**Issue by Sapu98** [serversigns/ServerSigns#50]
This is the command the sign should be running:
/mvtp <player> e:world:<r:-20000 20000>,100,<r:-20000 20000>
it seems like the execution stops at "e:" when I try to print the command as a <message>

**Comment by EpiCanard** [comment]
Hello,

There is an error in your command you need a dash between the two numbers

/mvtp e:world:<r:-20000-20000>,100,<r:-20000-20000>
