### ISSUE TITLE
Potential to integrate with MythicMobs?

### ISSUE THREAD

**Issue by aparry91** [serversigns/ServerSigns#55]
would it be possible to use the command functionality with MythicMob NPCs?

**Comment by EpiCanard** [comment]
Hello,

Can you explain with more details what is your needs ?

**Comment by aparry91** [comment]
I was wondering if it was possible to register the same signs functionality, with right clicking an NPC instead? - apologies if this is too farfetched I appreciate your plugin is for signs/blocks not entities

**Comment by EpiCanard** [comment]
I think it will be a lot of work to make it works for NPC.

Maybe you can try to create a custom command with MyCommand and have it executed by a plugin on right click on the mob.
I know you can execute command for Citizens but I don't know for MythicMob
