### ISSUE TITLE
play sound difficulties

### ISSUE THREAD

**Issue by aparry91** [serversigns/ServerSigns#56]
`/svs add <server> /playsound minecraft:entity.enderman.stare player <player>`

doesn't play a sound

**Comment by aparry91** [comment]
Does not work:
```
/svs add <server> /playsound minecraft:entity.enderman.stare player < player >
/svs add <server> /playsound minecraft:entity.enderman.stare player @p
/svs add /playsound minecraft:entity.enderman.stare player <player>
```

Works:
```
/svs add /playsound minecraft:entity.enderman.stare player @p
/svs add /playsound minecraft:entity.enderman.stare player @a
```

However even though it works, it only works for players with access to /playsound which causes issues
Please help!

Alternative has been to add [p:minecraft.command.playsound] : 
```
/svs add [p:minecraft.command.playsound] /playsound minecraft:entity.enderman.stare player @p
/svs add [p:minecraft.command.playsound] /playsound minecraft:entity.enderman.stare player @a
```

however still not working as I get error, Selector not allowed


Final way I got this working was :
`/svs add [p:minecraft.command.playsound] /playsound minecraft:entity.enderman.stare player <player>`

**Comment by EpiCanard** [comment]
Hello

You can let the console execute the command for you. No need to add permission 
`/svs add <server> playsound minecraft:entity.enderman.stare player <player>`

**Comment by aparry91** [comment]
> Hello
> 
> You can let the console execute the command for you. No need to add permission `/svs add <server> playsound minecraft:entity.enderman.stare player <player>`

no, I use the <server> functionality on many of my signs, but for some reason it is not compatible with playsound - I apologise I forgot to add <server> in the first mention of the issue

**Comment by aparry91** [comment]
ok turns out I didn't forget to mention it, its just not visible when you write it as a comment

**Comment by EpiCanard** [comment]
ok ok, I guess then only add temporary permission is possible
