### ISSUE TITLE
Question Not Bug

### ISSUE THREAD

**Issue by KingOfAllRats** [serversigns/ServerSigns#59]
No matter what I try I cant set a permission, I cant figure out how to make it so that everyone can use the placed server signs?
Any help would be extremely appreciated as im starting to lose my mind.

**Comment by EpiCanard** [comment]
Hello,
Which permission plugin do you use ?
The player must have the permission `serversigns.use.*`

**Comment by KingOfAllRats** [comment]
Im Using LuckPerm

**Comment by EpiCanard** [comment]
You can do `/lp group default permission set serversigns.use.*`
And if it still doesn't work maybe your sign is inside the spawn protection area
https://github.com/serversigns/ServerSigns/wiki/Frequently-Asked-Questions-%28FAQs%29#why-can-non-ops-with-correct-permissions-not-use-serversigns-i-have-created

**Comment by EpiCanard** [comment]
@KingOfAllRats Is your problem solved ?
