### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by JennaDiamonds** [serversigns/ServerSigns#6]
Would it be possible to disable use of signs when a player is in combat?
Long story:
I'm running an MMORPG. When a player wants to enter a house, for example, they click the door (which is an svs teleport) and gets ported into the house like in oldschool RPG games. There may be enemies in the house that need to be dispatched.. But I'd like to force a fight to the death instead of the player being able to flee by use of the door. Any help would be welcome :)

**Comment by EpiCanard** [comment]
If I well understand you want to be able to open the door without activate the svs command ?
How you can detect if a player is in combat mode ? If the player has a weapon inside hand ?

**Comment by EpiCanard** [comment]
You can maybe give permission when the player enter inside house and remove this permission when all players are dead ?
And while he have this permission it can't open the door.

Disable action with permission you can already do it with SVS but detect if there is alive players/mob inside an area it is not the goal of SVS.
Maybe some plugins exist to create a combat zone as desired.
