### ISSUE TITLE
Update 1.19.3

### ISSUE THREAD

**Issue by JoeDalton9027** [serversigns/ServerSigns#60]
Hello, is there any date planned for 1.19.3 support ?
Because since i change the server version, SVS stopped working.

Thanks :)

**Comment by EpiCanard** [comment]
Hello,

Can you send me the logs of your bug ?
Because on my server Serversigns works well on 1.19.3.

Thanks

**Comment by JoeDalton9027** [comment]
Hello, i think i shouldn't have the good version, because i try to re-install it and it works.
Sorry for having open a thread for this .. :)

**Comment by EpiCanard** [comment]
Hello
It's a good news :)
