### ISSUE TITLE
How to make server sign apply on button?

### ISSUE THREAD

**Issue by eswf** [serversigns/ServerSigns#62]
When i tried /svs create and right clicked the button it didnt worked? Can any1 please help?

**Comment by EpiCanard** [comment]
Hello @lammycz 

Did you try to change you config and add the buttons material name in the `blocks` list ?

By default this list contains signs but you can add every block you want.

**Comment by EpiCanard** [comment]
No answer, I close the issue.

Feel free to reopen the issue if you still have questions

**Comment by eswf** [comment]
Thank you it worked, I just forgot about this 😫
