### ISSUE TITLE
Gets detected as a Trojan.

### ISSUE THREAD

**Issue by ghost** [serversigns/ServerSigns#66]
The mod get detected as a Trojan with multiple security vendors.
[VirusTotal](https://www.virustotal.com/gui/file/03bd410204a3b4b473a8ac2cdd9acb6c91e6b35a6888fadaf1e913b67b9d0681)

![image](https://github.com/serversigns/ServerSigns/assets/122953693/a26a2e2e-d6f1-441a-b6da-bd24a2a9826c)

**Comment by EpiCanard** [comment]
Hello,

Where did you downloaded your version ?
Can you send me your jar to see if he is corrupted ?

You can find the source code of AdminListener [here](https://github.com/serversigns/ServerSigns/blob/master/src/main/java/de/czymm/serversigns/listeners/AdminListener.java) and there no trojan in this file.
Could be a false positive

**Comment by ghost** [comment]
I got the latest jar file from this repo.

**Comment by EpiCanard** [comment]
The jar available on this repo is auto generated from the source code.

I think your anti-virus is making mistakes because there is no malicious code in the projet neither external dependency that could inject malicious code.

**Comment by waseric** [comment]
As this is still an issue as of this date for all jars after v4.6.3, I used BitDefender's link to "Submit a File or a Website for malware analysis" at (https://www.bitdefender.com/consumer/support/answer/29358/)

Per BitDefender's last update:
"Our Malware Research Team has finished analyzing your case.

The file is clean and detection should be removed in the next couple of updates."
